### ISSUE TITLE
PLEASE REMOVE ALL FILES WITH ~

### ISSUE THREAD

**Issue by MNegus** [deanott/AMPD_Python#1]
# THE ONE THING
# THAT REALL
# GRIDFN S MY HJEDS ON GIHUB
# IS WHEN STUPID
# CHILDREN
# TRY TO USE IT
# AND DONT 
# DELETE THEIR FIELS 
# WITH THE FRICKIN
# THING
# -10/10 I WOULD NOT RECOMEND 

*love is all you need - David Cameron*

**Comment by deanott** [comment]
Thank you for the comment! Unfortunately I lost all my changes and borked everything trying to be too smart ... 
But stay strong! also na
